nelmio_cors:
    defaults:
        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
        expose_headers: ['Link']
        max_age: 3600
        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

        #  il faut que j'activer ces ligne et desactiver les lignes precedents qui sont associe a la section de defaults :
        # origin_regex: true
        # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        # allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        # allow_headers: ['Content-Type', 'Authorization']
        # expose_headers: ['Link']
        # max_age: 3600
        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
    paths:
        '^/': null
